IF
	Global("Action","LOCALS",1)
	!TimerActive(19)
	See(NearestEnemyOf(Myself),0)
THEN
	RESPONSE #100
		StartTimer(19,7)
		SetGlobal("Action","LOCALS",0)
		ReallyForceSpell(LastMarkedObject,INNATE_UMBER_HULK_GAZE)  // SPIN994.SPL (No such index)
		WaitAnimation(Myself,WALK)
		WaitAnimation(Myself,CONJURE)
		WaitAnimation(Myself,CAST)
END

IF
	See(NearestEnemyOf(Myself),0)
THEN
	RESPONSE #100
		SetGlobal("Action","LOCALS",1)
		EquipWeapon()
		AttackOneRound(LastMarkedObject)
END

