IF
	Or(3)
		!NumTimesTalkedTo(0)
		AttackedBy([GOODCUTOFF],DEFAULT)
		Global("Shaengarne_Bridge_Destroyed","GLOBAL",2)
THEN
	RESPONSE #100
		Enemy()
		Continue()
END

IF
	Or(2)
		!NumTimesTalkedTo(0)
		Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		ChangeCurrentScript("")
END

IF
	!Allegiance(Myself,ENEMY)
	CheckDoorFlags("AR2102_Bridge",DOOROPEN)
	LOS(NearestPC,28)
THEN
	RESPONSE #100
		SetDialogueRange(300)
		Dialogue(NearestPC)
END

