IF
	Global("LysaraTeamAttacked","MYAREA",0)
	AttackedBy([GOODCUTOFF],DEFAULT)
THEN
	RESPONSE #100
		SetGlobal("LysaraTeamAttacked","MYAREA",1)
END

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	!TimerActive(200)
THEN
	RESPONSE #100
		MoveToObject(LastAttackerOf(Myself))
		Continue()
END

IF
	Global("LysaraTeamAttacked","MYAREA",1)
	!TimerActive(200)
THEN
	RESPONSE #100
		MoveToObject(NearestPC)
		Continue()
END

IF
	!TimerActive(200)
THEN
	RESPONSE #100
		StartRandomTimer(200,7,14)
		Continue()
END

