IF
	GlobalTimerNotExpired("PrismFireDelay","MYAREA")
THEN
	RESPONSE #100
		NoAction()
END

IF
	Global("41PrismTarget","MYAREA",2)
	OpenState("AR4102_Door10",TRUE)
THEN
	RESPONSE #100
		TriggerActivation("ShadowTrap",FALSE)
		Unlock("AR4102_Door9")
		OpenDoor("AR4102_Door9")
		Continue()
END

IF
	Global("41PrismTarget","MYAREA",2)
THEN
	RESPONSE #100
		ForceSpellPoint([791.986],2092)  // SPWI092.SPL (No such index)
		TriggerActivation(Myself,FALSE)
END

