IF
	Global("41PrismFire","MYAREA",3)
	OpenState("AR4102_Door15",TRUE)
THEN
	RESPONSE #100
		ForceSpellPoint([1059.2516],2092)  // SPWI092.SPL (No such index)
		SetGlobalTimer("PrismFireDelay","MYAREA",2)
		TriggerActivation("Mirror4",TRUE)
		TriggerActivation(Myself,FALSE)
END

IF
	Global("41PrismFire","MYAREA",3)
	OpenState("AR4102_Door15",FALSE)
THEN
	RESPONSE #100
		ForceSpellPoint([1059.2516],2092)  // SPWI092.SPL (No such index)
		TriggerActivation(Myself,FALSE)
END

