IF
	True()
THEN
	RESPONSE #100
		CutSceneId("Saablic_Tan")
		MultiPlayerSync()
		Wait(1)
		ForceSpellPoint([0.0],WIZARD_DIMENSION_DOOR)  // SPWI402.SPL (Dimension Door)
		Wait(3)
		DestroySelf()
		EndCutSceneMode()
		MultiPlayerSync()
END

IF
	True()
THEN
	RESPONSE #100
		CutSceneId("Wanmok")
		MultiPlayerSync()
		Wait(2)
		ForceSpellPoint([0.0],WIZARD_DIMENSION_DOOR)  // SPWI402.SPL (Dimension Door)
		Wait(1)
		DestroySelf()
END

