# 210 - 1000 - reserved for globals

GVAR_KEEP_QUORIS_SUMMON_1_STATE = 100

GVAL_KEEP_QUORIS_SUMMON_1_STATE_NONE = 0
GVAL_KEEP_QUORIS_SUMMON_1_STATE_COMBAT = 1
GVAL_KEEP_QUORIS_SUMMON_1_STATE_WON = 2
GVAL_KEEP_QUORIS_SUMMON_1_STATE_REACTED = 3

#GFLAG_KEEP_SHANIA_CAN_DECIPHER_INFORMED = 100
#GFLAG_KEEP_KAREF_SW_CAVES_INFORMED = 101

GFLAG_KNOWN_CORINTH = 200
GFLAG_KNOWN_CAVES = 201

GFLAG_ORC_FORT_SKIP_ASSAULT = 222
GFLAG_ORC_FORT_WITCH_HELP = 223
